version: "3.7"
services:

  mysql:
    image: mysql:5.7
    env_file: mysql/create.env
    volumes:
      - ./db_data/:/var/lib/mysql/
      - ./mysql/create.sql:/docker-entrypoint-initdb.d/000_create.sql
    ports:
      - 127.0.0.1:3306:3306